defaults:
  - hydra/job_logging: bohb_full
  - benchmark: fcnet
  - approach: gp
  - runtype: eval_dim

experiment_group: test
experiment_name: test_${run_id}
run_id: ${now:%Y-%m-%d-%H-%M-%S}
worker_id: 0
seed: 2
nic_name: lo
reference_losses_path: hp_transfer_aa_experiments/reference_losses.yaml

hydra:
  run:
    dir: results/${experiment_group}/${experiment_name}
