defaults:
  - hydra/job_logging: bohb
  - hydra/launcher: submitit_slurm
  - benchmark: ???
  - approach: ???
  - runtype: ???

seed: ???
run_id: ${seed}
experiment_group: ???
experiment_name: ${benchmark.name}/${runtype.type}/${approach.name}/trajectory_id_${benchmark.benchmark.trajectory_id}/adjustment_id_${benchmark.benchmark.adjustment_id}/id_${run_id}
worker_id: 0
nic_name: eth0
reference_losses_path: hp_transfer_aa_experiments/reference_losses.yaml

hydra:
  sweep:
    dir: results/${experiment_group}
    subdir: ${experiment_name}

  launcher:
    pre_execute_command: source ~/.conda/bin/activate htaa
    execute_command: python hp_transfer_aa_experiments.run.py
    time: 0-02:00
    cpus_per_task: 1
    gpus: 0
    mem_per_cpu: 8000
    job_name: ${benchmark.name}_${approach.name}
    partition: ???
    # max_parallel_jobs:
    error: ${hydra.sweep.dir}/cluster_oe/%A_%x_%t.oe
    output: ${hydra.sweep.dir}/cluster_oe/%A_%x_%t.oe
