defaults:
  - benchmark: ???
  - approach: ???
  - runtype: ???
  - _self_
  - override hydra/job_logging: bohb
  - override hydra/launcher: script

seed: ???
run_id: ${seed}
experiment_group: ???
experiment_name: ${benchmark.name}/${runtype.type}/${approach.name}/trajectory_id_${benchmark.benchmark.trajectory_id}/adjustment_id_${benchmark.benchmark.adjustment_id}/id_${run_id}
worker_id: 0
nic_name: lo
reference_losses_path: hp_transfer_aa_experiments/reference_losses.yaml

cluster:
  partition: ???
  max_array_tasks: 100

hydra:
  launcher:
    pre_command: "mkdir ${hydra.sweep.dir}/cluster_oe -p"
    batch_script_template: |
      #!/bin/bash
      #SBATCH --time 0-01:00
      #SBATCH --job-name test
      #SBATCH --output ${hydra.sweep.dir}/cluster_oe/%A_%x_%t.oe
      #SBATCH --error ${hydra.sweep.dir}/cluster_oe/%A_%x_%t.oe
      #SBATCH --array 1-<PUT_NUM_ARGS>%${cluster.max_array_tasks}
      #SBATCH --partition ${cluster.partition}
      <PUT_ARGS>
      conda activate htaa_imcl
      python -m hp_transfer_aa_experiments.run --config-name run_meta <PUT_DOLLAR>{ARGS[$(($SLURM_ARRAY_TASK_ID-1))]}
  sweep:
    dir: results/${experiment_group}
    subdir: ${experiment_name}
  run:
    dir: ${hydra.sweep.dir}/${hydra.sweep.subdir}
